[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "18"
  # IMPORTANT: Set this in Netlify Dashboard → Site Settings → Environment Variables
  # VITE_API_URL = "https://your-backend-url.com/api/v1"
  # 
  # Backend deployment options:
  # - Railway: https://your-app-name.railway.app/api/v1
  # - Render: https://your-app-name.onrender.com/api/v1
  # - Heroku: https://your-app-name.herokuapp.com/api/v1
  # - DigitalOcean: https://your-app-name.ondigitalocean.app/api/v1

# API proxy redirects
# Update the 'to' URL after deploying your backend
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

# SPA routing - all other routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
