services:
  # PostgreSQL Database
  - type: pserv
    name: university-verifier-db
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.db
    envVars:
      - key: POSTGRES_DB
        value: university_verifier
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Backend API Service
  - type: web
    name: university-verifier-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: university-verifier-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: UPLOAD_DIR
        value: "/app/uploads"
      - key: MAX_FILE_SIZE
        value: "10485760"
    healthCheckPath: /api/v1/health

  # Frontend React App
  - type: web
    name: university-verifier-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: university-verifier-backend
          type: web
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # University Portal
  - type: web
    name: university-verifier-portal
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./university-portal/Dockerfile
    dockerContext: ./university-portal
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: university-verifier-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
